# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: main
    vol_size: 10

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: face_recognition
    volumes: ['main']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: id_team06
instance_flavor: uom.mse.2c9g
